#!/bin/bash
# Ask the user for their email address
echo Email:
read EMAIL
export EMAIL=$EMAIL
envsubst < /usr/local/bin/calico_installer.yaml | kubectl apply -f -
sleep 1
echo
echo =================
kubectl describe installer -n calico-cloud   default  | grep Message
# echo Please accept the Calico Cloud invitation sent to your email. This account is valid for 24 hours. 
# echo Open the email, fill in the brief onboarding dialog, and in about 5 minutes, your cluster will open in the Calico Cloud user interface. That’s it. You’re ready to go!
echo
