#!/bin/bash
# Ask the user for their email address
echo Email:
read EMAIL
kubectl apply -f /usr/local/bin/calico_installer.yaml 
echo
echo =================
echo We have sent you an invitation to access Calico cloud. this account is valid for 24 hours. 
echo Open the email, fill in the brief onboarding dialog, and in about 5 minutes, your cluster will open in the Calico Cloud user interface. That’s it. You’re ready to go!
echo
